const mongoose = require("mongoose");
const Category = require("../model/categoryModel");

const antiqueCategories = [
  {
    title: "Furniture",
    description: "Antique and vintage furniture pieces including chairs, tables, cabinets, and decorative furniture",
    slug: "furniture",
    categoryType: "Furniture",
    expertiseRequired: true,
    averageValue: { min: 100, max: 50000 },
    popularEras: ["Victorian", "Georgian", "Art Deco", "Mid-Century Modern"],
    sortOrder: 1,
    subcategories: [
      {
        title: "Chairs & Seating",
        description: "Antique chairs, sofas, benches, and other seating furniture",
        slug: "chairs-seating",
        categoryType: "Furniture",
        averageValue: { min: 50, max: 15000 },
        sortOrder: 1,
      },
      {
        title: "Tables & Desks",
        description: "Dining tables, writing desks, side tables, and work surfaces",
        slug: "tables-desks",
        categoryType: "Furniture",
        averageValue: { min: 100, max: 25000 },
        sortOrder: 2,
      },
      {
        title: "Storage & Cabinets",
        description: "Wardrobes, chests, bookcases, and storage furniture",
        slug: "storage-cabinets",
        categoryType: "Furniture",
        averageValue: { min: 200, max: 30000 },
        sortOrder: 3,
      },
    ],
  },
  {
    title: "Jewelry & Watches",
    description: "Antique and vintage jewelry, timepieces, and personal accessories",
    slug: "jewelry-watches",
    categoryType: "Jewelry",
    expertiseRequired: true,
    averageValue: { min: 50, max: 100000 },
    popularEras: ["Victorian", "Edwardian", "Art Nouveau", "Art Deco"],
    sortOrder: 2,
    subcategories: [
      {
        title: "Rings",
        description: "Antique rings including engagement, wedding, and statement rings",
        slug: "rings",
        categoryType: "Jewelry",
        averageValue: { min: 100, max: 50000 },
        sortOrder: 1,
      },
      {
        title: "Necklaces & Pendants",
        description: "Vintage necklaces, chains, and pendant jewelry",
        slug: "necklaces-pendants",
        categoryType: "Jewelry",
        averageValue: { min: 75, max: 25000 },
        sortOrder: 2,
      },
      {
        title: "Watches & Timepieces",
        description: "Antique pocket watches, wristwatches, and clocks",
        slug: "watches-timepieces",
        categoryType: "Jewelry",
        averageValue: { min: 200, max: 75000 },
        sortOrder: 3,
      },
    ],
  },
  {
    title: "Art & Paintings",
    description: "Original artworks, paintings, prints, and sculptures",
    slug: "art-paintings",
    categoryType: "Art & Paintings",
    expertiseRequired: true,
    averageValue: { min: 100, max: 500000 },
    popularEras: ["Renaissance", "Baroque", "Impressionist", "Modern"],
    sortOrder: 3,
    subcategories: [
      {
        title: "Oil Paintings",
        description: "Original oil paintings and canvas works",
        slug: "oil-paintings",
        categoryType: "Art & Paintings",
        averageValue: { min: 200, max: 200000 },
        sortOrder: 1,
      },
      {
        title: "Prints & Etchings",
        description: "Lithographs, etchings, engravings, and limited edition prints",
        slug: "prints-etchings",
        categoryType: "Art & Paintings",
        averageValue: { min: 50, max: 10000 },
        sortOrder: 2,
      },
      {
        title: "Sculptures",
        description: "Bronze, marble, and other sculptural works",
        slug: "sculptures",
        categoryType: "Art & Paintings",
        averageValue: { min: 300, max: 100000 },
        sortOrder: 3,
      },
    ],
  },
  {
    title: "Ceramics & Pottery",
    description: "Antique porcelain, pottery, china, and ceramic artworks",
    slug: "ceramics-pottery",
    categoryType: "Ceramics & Pottery",
    expertiseRequired: true,
    averageValue: { min: 25, max: 25000 },
    popularEras: ["Ming Dynasty", "Victorian", "Art Nouveau", "Mid-Century Modern"],
    sortOrder: 4,
    subcategories: [
      {
        title: "Porcelain & China",
        description: "Fine porcelain, bone china, and ceramic dinnerware",
        slug: "porcelain-china",
        categoryType: "Ceramics & Pottery",
        averageValue: { min: 50, max: 15000 },
        sortOrder: 1,
      },
      {
        title: "Art Pottery",
        description: "Studio pottery, art ceramics, and decorative vessels",
        slug: "art-pottery",
        categoryType: "Ceramics & Pottery",
        averageValue: { min: 100, max: 10000 },
        sortOrder: 2,
      },
    ],
  },
  {
    title: "Textiles & Fashion",
    description: "Vintage clothing, textiles, quilts, and fashion accessories",
    slug: "textiles-fashion",
    categoryType: "Textiles",
    expertiseRequired: false,
    averageValue: { min: 25, max: 5000 },
    popularEras: ["Victorian", "Edwardian", "1920s", "1950s"],
    sortOrder: 5,
  },
  {
    title: "Books & Manuscripts",
    description: "Rare books, manuscripts, maps, and printed materials",
    slug: "books-manuscripts",
    categoryType: "Books & Manuscripts",
    expertiseRequired: true,
    averageValue: { min: 20, max: 50000 },
    popularEras: ["Medieval", "Renaissance", "18th Century", "19th Century"],
    sortOrder: 6,
  },
  {
    title: "Coins & Currency",
    description: "Antique coins, paper money, and numismatic collectibles",
    slug: "coins-currency",
    categoryType: "Coins & Currency",
    expertiseRequired: true,
    averageValue: { min: 10, max: 100000 },
    popularEras: ["Ancient", "Medieval", "Colonial", "Modern"],
    sortOrder: 7,
  },
  {
    title: "Vintage Collectibles",
    description: "Collectible items, memorabilia, and vintage objects",
    slug: "vintage-collectibles",
    categoryType: "Vintage Collectibles",
    expertiseRequired: false,
    averageValue: { min: 15, max: 10000 },
    popularEras: ["Victorian", "Art Deco", "Mid-Century Modern", "1960s"],
    sortOrder: 8,
  },
  {
    title: "Decorative Arts",
    description: "Decorative objects, ornaments, and functional art pieces",
    slug: "decorative-arts",
    categoryType: "Decorative Arts",
    expertiseRequired: false,
    averageValue: { min: 30, max: 15000 },
    popularEras: ["Art Nouveau", "Art Deco", "Victorian", "Georgian"],
    sortOrder: 9,
  },
  {
    title: "Musical Instruments",
    description: "Antique and vintage musical instruments",
    slug: "musical-instruments",
    categoryType: "Musical Instruments",
    expertiseRequired: true,
    averageValue: { min: 100, max: 75000 },
    popularEras: ["Baroque", "Classical", "Romantic", "Modern"],
    sortOrder: 10,
  },
];

module.exports = antiqueCategories;
